config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end

  root "pins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  acts_as_votable
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order("created_at DESC")
  end

  def new
    @pin = current_user.pins.build
  end

  def show
    @pins = Pin.all
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: "Successfully created new Pin"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Pin was successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path
  end

  def upvote
    @pin.upvote_by current_user
    redirect_back fallback_location: root_path
  end

  private
  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Pin Board
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-default
      .container
        .navbar-brand= link_to "Pin Board", root_path

        -if user_signed_in?
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "New Pin", new_pin_path
            %li= link_to "Account", edit_user_registration_path
            %li= link_to "Sign out", destroy_user_session_path, method: :delete
        -else
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Sign Up", new_user_registration_path
            %li= link_to "Sign In", new_user_session_path
    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: "alert alert-info"
      = yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: {multipart: true } do |f|
  - if @pin.errors.any?
    #errors
      %h2
      =pluralize(@pin.errors.count, "error")
      prevented this Pin from saving
      %ul
        - @pin.errors.full_messages.each do |msg|
          %li = msg
  .form_group
    = f.input :image, input_html: {class: 'form-control'}

  .form_group
    = f.input :title, input_html: {class: 'form-control'}
  .form_group
    = f.input :description, input_html: {class: 'form-control'}
  =f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit Your Pin
			.panel-body
				.current_image
					%strong.center Current Image
					= image_tag @pin.image.url(:medium)
				= render 'form'

app/views/pins/index.html.haml
#pins.transitions-enabled
  - @pins.each do |pin|
    .box.panel.panel-default
      =link_to (image_tag pin.image.url), pin
      .panel-body
        %h2= link_to pin.title, pin
        %p.user
        Submitted by
        =pin.user.email

app/views/pins/new.html.haml
.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Create A New Pin
			.panel-body
				= render 'form'

app/views/pins/show.html.haml
#pin_show.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading.pin_image
        = image_tag @pin.image.url
      .panel-body
        %h1= @pin.title
        %p.description= @pin.description
      .panel-footer
        .row
          .col-md-6
            %p.user
            Submitted by
            =@pin.user.email
          .col-md-6
            .btn-group.pull-right
              = link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
                %span.glyphicon.glyphicon-heart
                  = @pin.get_upvotes.size
              -if @pin.user == current_user
                = link_to "Edit", edit_pin_path, class: "btn btn-default"
                = link_to "Delete", pin_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default"